version: "2"

services:
  # The Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: roerjo/php-todo-app
    container_name: php-todo-app
    working_dir: /var/www/app
    expose:
      - 9000
    links:
      - database

  # The Web Server
  nginx:
    image: nginx:alpine
    container_name: php-todo-nginx
    expose:
      - 80
    volumes:
      - ./vhost.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/app
    links:
      - app
    environment:
      - "VIRTUAL_HOST=${APP_HOST}"
      - "LETSENCRYPT_HOST=${APP_HOST}"
      - "LETSENCRYPT_EMAIL=${APP_EMAIL}"

  # The Local Database
  database:
    image: mysql:5.7
    container_name: php-todo-database
    volumes:
      - php_todo_database:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=${DATABASE_DATABASE}"
      - "MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}"
    ports:
      - "${EXTERNAL_DB_PORT}:3306"

volumes:
  php_todo_database:

networks:
  default:
    external:
      name: nginx-proxy
