name: Push Flow

on: push

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-scripts --no-suggest --no-progress --prefer-dist
    - name: Install SQLite
      run: sudo apt-get install -y sqlite3
    - name: Setup Environment
      run: php -r "copy('.env.ci', '.env');"
    - name: Setup Database
      run: echo .read migrations/sqlite/create_tasks_table_20190924072400.sql | sqlite3
    - name: Run tests
      run: vendor/bin/phpunit tests --bootstrap=vendor/autoload.php
    - name: Upload Server Report
      uses: actions/upload-artifact@v1
      with:
        name: server-report
        path: phpd.log
