name: Push Flow

on: push

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Install Dependencies
        run: composer install

      - name: Run tests
        run: vendor/bin/phpunit

      - name: Upload Server Report
        uses: actions/upload-artifact@v1
        with:
          name: server-report
          path: phpd.log
