name: Push Flow

on: push

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-scripts --no-suggest --no-progress --prefer-dist
    - name: Install SQLite
      run: sudo apt-get install -y sqlite3
    - name: Setup Database
      run: echo .read migrations/sqlite/create_tasks_table_20190924072400.sql | sqlite3
    - name: Run tests
      run: vendor/bin/phpunit tests
