name: Push Flow

on: push

jobs:
  format:
    name: Format Code
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, gd
          coverage: none
          tools: composer:v1

      - name: Install Dependencies
        run: composer install -n --no-ansi --no-interaction --no-scripts --no-suggest --no-progress

      - name: Run php-cs-fixer
        run: ./vendor/bin/php-cs-fixer fix --config=.php-cs.php --diff

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply php-cs-fixer changes

  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, gd
          coverage: none
          tools: composer:v1

      - name: Install Dependencies
        run: composer install -n --no-ansi --no-interaction --no-scripts --no-suggest --no-progress

      - name: Run tests
        run: vendor/bin/phpunit

      - name: Upload Server Report
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: test-run-report
          path: ./storage/logs
