name: Push Flow

on: push

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-scripts --no-suggest --no-progress --prefer-dist
    - name: Install SQLite
      run: sudo apt-get install -y sqlite3
    - name: Setup Environment
      run: php -r "copy('.env.ci', '.env');"
    - name: Setup Database
      run: echo .read migrations/sqlite/create_tasks_table_20190924072400.sql | sqlite3
    - name: Run PHP Server In Background
      run: nohup php -S localhost:8080 -t public > phpd.log 2>&1 &
    - name: Run tests
      run: |
        cat phpd.log
        vendor/bin/phpunit tests
        cat phpd.log
